name: Todo
description: Something to do
title: "[TODO] "
labels: ["todo"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      placeholder: what needs to be done
    validations:
      required: true

  - type: textarea
    id: note
    attributes:
      label: Note (optional)
      placeholder: links / context
    validations:
      required: false
